### ISSUE TITLE
Pinokio script version too high 

### ISSUE THREAD

**Issue by 6Morpheus6** [IAHispano/Applio-Pinokio#3]
Hi :)
The script version set in [line 3 of pinokio.js](https://github.com/IAHispano/Applio-Pinokio/blob/54ea4ba63b2e3b5b1e409e0008c114df70013474/pinokio.js#L3) is too high and triggers an update warning in Pinokio although Pinokio is updated to the latest version.
Please set it to `version: "2.1.0",`

![image](https://github.com/user-attachments/assets/37abc797-cb9a-4113-b1e0-51ea58fc7e32)

**Comment by blaisewf** [comment]
oh, yeah let me fix that
