### ISSUE TITLE
omegaconf 2.0.5 not compatible with python 3.9 due to metadata error

### ISSUE THREAD

**Issue by 6Morpheus6** [IAHispano/Applio-Pinokio#4]
omegaconf 2.0.5 has a metadata error. Pip 24.1 or greater refuses to install it.
other versions of omegaconf need python 3.10 or higher.
If a virtual env is possible in Applio, it would automatically use python 3.10.14 in Pinokio.
Here the error output in Pinokio
```
WARNING: Ignoring version 2.0.5 of omegaconf since it has invalid metadata:
Requested omegaconf==2.0.5 from https://files.pythonhosted.org/packages/e5/f6/
043b6d255dd6fbf2025110cea35b87f4c5100a181681d8eab496269f0d5b/omegaconf-2.0.5-py3-none-any.whl
(from -r requirements.txt (line 26)) has invalid metadata: .* suffix can
only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Ignored the following yanked versions: 1.0.0, 1.0.1, 1.0.2, 2.0.0rc1, 2.0.0rc2, 2.0.0rc22, 2.0.0rc23,
2.0.0rc24, 2.0.0rc25, 2.0.0rc26, 2.0.0rc27, 2.0.0rc28, 2.0.0rc29, 2.0.1rc1, 2.0.1rc2, 2.0.1rc3, 2.0.1rc4, 2.0.1rc5, 2.2.0
ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10;
1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 1.14.1 Requires-Python >=3.10;
2.1.0 Requires-Python >=3.10; 2.1.0rc1 Requires-Python >=3.10; 2.1.1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement omegaconf==2.0.5
ERROR: No matching distribution found for omegaconf==2.0.5
```

Quick omegaconf 2.0.5 test I made in a test environment with python 3.10.14

![image](https://github.com/user-attachments/assets/20e0ee84-7796-49cb-9ec2-26092a734d1d)

**Comment by blaisewf** [comment]
you can follow this https://github.com/IAHispano/Applio/blob/53ff2cb0a00a2c0b63dee0ee951b39b3da44e4e1/run-install.bat#L51

**Comment by blaisewf** [comment]
i don't use pinokio neither this installer was made by, so if you want to push a fix for it would be good, the recommended version is 3.9.10

**Comment by 6Morpheus6** [comment]
> i don't use pinokio neither this installer was made by, so if you want to push a fix for it would be good, the recommended version is 3.9.10

@blaisewf So you fix this problem by downgrading / installing pip<24.1 ?
This could be added in install.js before installing the requirements.
```
 message: [
          "python.exe -m pip install pip<24.1" 
          "pip install --upgrade setuptools",
          "pip install -r requirements.txt",
          "pip uninstall torch torchvision torchaudio -y",
          "pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121",
        ],
        ```
You could give it a try and I would test it with the user having this problem. If it doesn't work I can fork the project and see which other fixes could work.

**Comment by blaisewf** [comment]
> > i don't use pinokio neither this installer was made by, so if you want to push a fix for it would be good, the recommended version is 3.9.10
> 
> @blaisewf So you fix this problem by downgrading / installing pip<24.1 ? This could be added in install.js before installing the requirements.
> 
> ```
>  message: [
>           "python.exe -m pip install pip<24.1",
>           "pip install --upgrade setuptools",
>           "pip install -r requirements.txt",
>           "pip uninstall torch torchvision torchaudio -y",
>           "pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121",
>         ],
>         ```
> You could give it a try and I would test it with the user having this problem. If it doesn't work I can fork the project and see which other fixes could work.
> ```

yes, that fixes

**Comment by 6Morpheus6** [comment]
> > > i don't use pinokio neither this installer was made by, so if you want to push a fix for it would be good, the recommended version is 3.9.10
> > 
> > 
> > @blaisewf So you fix this problem by downgrading / installing pip<24.1 ? This could be added in install.js before installing the requirements.
> > ```
> >  message: [
> >           "python.exe -m pip install pip<24.1",
> >           "pip install --upgrade setuptools",
> >           "pip install -r requirements.txt",
> >           "pip uninstall torch torchvision torchaudio -y",
> >           "pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121",
> >         ],
> >         ```
> > You could give it a try and I would test it with the user having this problem. If it doesn't work I can fork the project and see which other fixes could work.
> > ```
> 
> yes, that fixes

Could you apply this to install.js please? We would test it. :)

**Comment by blaisewf** [comment]
feel free to open pr

**Comment by 6Morpheus6** [comment]
> feel free to open pr

Done. :)

**Comment by blaisewf** [comment]
nice, so you don't need this repository anymore?

**Comment by blaisewf** [comment]
![{79A43A15-5EAA-4F53-94F2-3780B49017C5}](https://github.com/user-attachments/assets/59b4cd23-6bb9-4b63-a860-f2b4201d173a)

🥲
